const LOADING = 'LOADING';
const GET_PROFILE = 'GET_PROFILE';
const ERROR = 'ERROR';
const USER_INPUT = 'USER_INPUT';
const AUDIO_NODE = 'AUDIO_NODE';

export { 
  LOADING, 
  GET_PROFILE, 
  ERROR,
  USER_INPUT,
  AUDIO_NODE
 };
 